// let a = 'hello';
// alert(a);document.write(a);
// console.log(a);
// let b = 'owu';
// alert(b);document.write(b);
// console.log(b);
// let c = 'com';
// alert(c);document.write(c);
// console.log(c);
// let d = 'ua';
// alert(d);document.write(d);
// console.log(d);
// let e = 1;
// alert(e);document.write(e);
// console.log(e);
// let f = 10;
// alert(f);document.write(f);
// console.log(f);
// let g = -999;
// alert(g);document.write(g);
// console.log(g);
// let h = 123;
// alert(h);document.write(h);
// // console.log(h);
// let i = 3.14;
// alert(i);document.write(i);
// console.log(i);
// let j = 2.7;
// alert(j);document.write(j);
// console.log(j);
// let k = 16;
// alert(k);document.write(k);
// console.log(k);
// let l = true;
// alert(l);document.write(l);
// console.log(l);
// let m = false;
// alert(m);document.write(m);
// console.log(m);
// let firstname = 'Володимир';
// let middlename = 'Остапович';
// let lastname = 'Шидловський';
// console.log(firstname + ' ' + middlename + ' ' + lastname);
// console.log(`${firstname} ${middlename} ${lastname}`);
// let person = {firstname: 'Volodymyr', middlename: 'Ostapovych', lastname: 'Shydlovskyy', age: 33};
// console.log(person.firstname);
// console.log(person.middlename);
// console.log(person.age);
// document.write('Вітаю' + ' ' + firstname +' '+ middlename + '.');
// document.write('Тобі' +' '+ person.age );
// let a = 100;let b = '100';let c = true;
// console.log(typeof a);
// console.log(typeof b);
// console.log(typeof c);
//
// let str = "20";
// let a = 5;
// document.write(str + a+ "br/>");
// document.write(str-a+"br/>");
// document.write(str*"2"+"br/>");
// document.write(str/2+"br/>");
